name: Testing site config
type: profile
description: 'Minimal profile for testing with default site config.'
# version: VERSION
hidden: true

# Information added by Drupal.org packaging script on 2023-08-02
version: '10.1.2'
project: 'drupal'
datestamp: 1690972232
